### ISSUE TITLE
Invalid type -8

### ISSUE THREAD

**Issue by Artur-** [evanw/kiwi#37]
While trying to parse data from Figma, it sometimes contains 
```
field {
  name: 'mentionedUserIdInt',
  line: 0,
  column: 0,
  type: -8,
  isArray: false,
  isDeprecated: false,
  value: 6
}
field {
  name: 'mentionedByUserIdInt',
  line: 0,
  column: 0,
  type: -8,
  isArray: false,
  isDeprecated: false,
  value: 7
}
```

which results in `Invalid type -8` being thrown.

Any clues what type 8 is (https://github.com/evanw/kiwi/blob/master/js/binary.ts#L4 only has 6 types)? 
Also, if you are still maintaining this lib, would there be a way to ignore the unknown types instead of throwing an error?

**Comment by evanw** [comment]
Caveat: I no longer work at Figma and have no insight as to what goes on over there. If you look at their schema (which is embedded in the JavaScript code in plain text), the definition of these properties is here:

```protobuf
message Mention {
  GUID id = 1;
  string mentionedUserId = 2;
  string mentionedByUserId = 3;
  string fileKey = 4;
  MentionSource source = 5;
  uint64 mentionedUserIdInt = 6;
  uint64 mentionedByUserIdInt = 7;
}
```

There is no `uint64` type in kiwi. So I assume they have forked this library internally and are now using their own divergent serialization format. It's not possible to ignore unknown types because advancing past something in a kiwi message requires knowing what it is.

**Comment by evanw** [comment]
There. I just published an update so type -8 should in theory be supported now. I'm curious: does this update fix the parsing of files that didn't parse before?

**Comment by Artur-** [comment]
That's amazing man! Now it parses the files without any issues

**Comment by darknoon** [comment]
Much appreciated! Could you publish an update to npm with this fix?

**Comment by evanw** [comment]
But I already did publish an update. That’s why I commented saying “I just published an update“ above. I’m confused.

**Comment by darknoon** [comment]
Ah, I looked at the 0.5.0 version number in npm, [published 2 months ago](https://www.npmjs.com/package/kiwi-schema?activeTab=versions) which afaik corresponds to 22d186c, and saw that 1cfffacade0054ba1eff9dbe7bfd10906ac2ddd4 wasn't included. I assumed it was needed since I was still seeing `Error: Invalid type -8` , but it turned out to be an issue with my setup.

Sorry for the confusion!
